# Generated by Django 3.1.8 on 2021-07-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210701_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadphoto',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
