# Generated by Django 3.1.8 on 2021-07-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210708_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadphoto',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
