# Generated by Django 3.1.8 on 2021-07-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_uploadphoto_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadphoto',
            name='officer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
