# Generated by Django 3.1.8 on 2021-07-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_uploadphoto_officer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadphoto',
            name='officer_name',
        ),
        migrations.RemoveField(
            model_name='uploadphoto',
            name='position',
        ),
    ]
