# Generated by Django 3.1.8 on 2021-07-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210711_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlist',
            name='position',
            field=models.CharField(choices=[('member', 'MEMBER'), ('president', 'PRESIDENT'), ('vice president', 'VICE PRESIDENT'), ('secretary', 'SECRETARY'), ('treasurer', 'TREASURER'), ('auditor', 'AUDITOR'), ('adviser', 'ADVISER'), ('coordinator', 'COORDINATOR'), ('collector', 'COLLECTOR')], max_length=20),
        ),
    ]
