# Generated by Django 3.1.8 on 2021-07-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210711_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.CharField(max_length=500)),
                ('when', models.CharField(max_length=20)),
                ('where', models.CharField(max_length=100)),
            ],
        ),
    ]
