# Generated by Django 3.1.8 on 2021-07-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_fileupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='pdf',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
