# Generated by Django 3.1.8 on 2021-07-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20210714_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
